name: GitHub-Profile-Summary-Cards

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          BRANCH_NAME: "main"
          UTC_OFFSET: 8
          EXCLUDE: ""
          AUTO_PUSH: false
      - name: Commit and push generated cards
        run: |
          git config user.name "PerinbaBuilds"
          git config user.email "perinbaathiban@gmail.com"
          git add profile-summary-card-output
          git diff --cached --quiet && exit 0
          git commit -m "Generate profile summary cards"
          git push
